services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - 10000:10000
      - 10001:10001/tcp
      - 10001:10001/udp
      - 9901:9901
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy/certs:/etc/envoy/certs:ro
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
